/*
 * The MIT License
 *
 * Copyright 2023 dssilva21.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package samuel.projeto.individual;

import com.github.britooo.looca.api.group.memoria.Memoria;
import com.github.britooo.looca.api.group.processador.Processador;
import com.github.britooo.looca.api.group.sistema.Sistema;
import com.github.britooo.looca.api.group.temperatura.Temperatura;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;

/**
 *
 * @author dssilva21
 */
public class Logado extends javax.swing.JFrame {
    
   private void iniciar() {
    new Timer().scheduleAtFixedRate(new TimerTask() {
        Sistema sistema = new Sistema();
        Memoria memoria = new Memoria();
        Temperatura temperatura = new Temperatura();
        Processador processador = new Processador();

        @Override
        public void run() {
            // Atualizar os valores das strings a cada execução
            String textoMemoriaEmUso = String.format("Memoria ram em uso: %.2f", memoria.getEmUso());
            String textoMemoriaDisponivel = String.format("Memoria ram disponivel: %.2f", memoria.getDisponivel());
            String textoMemoriaTotal = String.format("Memoria ram Total: %.2f", memoria.getTotal());
            String textoTemperatura = String.format("Temperatura atual: %.2f", temperatura.getTemperatura());
            String textoCpuEmUso = String.format("Cpu em uso : %.2f", processador.getUso());
            String textoNomeDoUsuario = "Nome do usuario : Samuel";

            // Atualizar as labels com os novos valores
            jLabelCpuEmUso.setText(textoCpuEmUso);
            jLabelMemoriaRamDisponivel.setText(textoMemoriaDisponivel);
            jLabelMemoriaRamEmUso.setText(textoMemoriaEmUso);
            jLabelMemoriaRamTotal.setText(textoMemoriaTotal);
            jLabelTemperaturaAtual.setText(textoTemperatura);
            jLabelNomeDoUsuario.setText(textoNomeDoUsuario);
            jLabelNumeroDeIdentificacaoDoTotem.setText("Numero de Identificação do totem: 1");
        }
    }, 0, 10000);
}
  /**
     * Creates new form Logado
     */
    public Logado() {
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeDoUsuario = new javax.swing.JLabel();
        jLabelNumeroDeIdentificacaoDoTotem = new javax.swing.JLabel();
        jLabelMemoriaRamEmUso = new javax.swing.JLabel();
        jLabelCpuEmUso = new javax.swing.JLabel();
        jLabelTemperaturaAtual = new javax.swing.JLabel();
        jLabelMemoriaRamDisponivel = new javax.swing.JLabel();
        jLabelMemoriaRamTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNomeDoUsuario.setText("Nome do usuario:");

        jLabelNumeroDeIdentificacaoDoTotem.setText("Numero de Identificação do totem: ");

        jLabelMemoriaRamEmUso.setText("Memoria Ram em uso: ");

        jLabelCpuEmUso.setText("Cpu em uso:");

        jLabelTemperaturaAtual.setText("Temperatura atual:");

        jLabelMemoriaRamDisponivel.setText("Memoria Ram disponivel:");

        jLabelMemoriaRamTotal.setText("Memoria Ram Total: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMemoriaRamDisponivel)
                            .addComponent(jLabelTemperaturaAtual)
                            .addComponent(jLabelMemoriaRamTotal)
                            .addComponent(jLabelCpuEmUso))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelMemoriaRamEmUso)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNomeDoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNumeroDeIdentificacaoDoTotem)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelNomeDoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNumeroDeIdentificacaoDoTotem)
                .addGap(41, 41, 41)
                .addComponent(jLabelMemoriaRamEmUso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMemoriaRamDisponivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMemoriaRamTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCpuEmUso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTemperaturaAtual)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String email, String senha) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logado().setVisible(true);
                TesteApi testeApi = new TesteApi();
                testeApi.main(email, senha);
            }
        });
        
    }

    public JLabel getjLabelCpuEmUso() {
        return jLabelCpuEmUso;
    }

    public void setjLabelCpuEmUso(JLabel jLabelCpuEmUso) {
        this.jLabelCpuEmUso = jLabelCpuEmUso;
    }

    public JLabel getjLabelMemoriaRamEmUso() {
        return jLabelMemoriaRamEmUso;
    }

    public void setjLabelMemoriaRamEmUso(JLabel jLabelMemoriaRamEmUso) {
        this.jLabelMemoriaRamEmUso = jLabelMemoriaRamEmUso;
    }


    public JLabel getjLabelNomeDoUsuario() {
        return jLabelNomeDoUsuario;
    }

    public void setjLabelNomeDoUsuario(JLabel jLabelNomeDoUsuario) {
        this.jLabelNomeDoUsuario = jLabelNomeDoUsuario;
    }

    public JLabel getjLabelNumeroDeIdentificacaoDoTotem() {
        return jLabelNumeroDeIdentificacaoDoTotem;
    }

    public void setjLabelNumeroDeIdentificacaoDoTotem(JLabel jLabelNumeroDeIdentificacaoDoTotem) {
        this.jLabelNumeroDeIdentificacaoDoTotem = jLabelNumeroDeIdentificacaoDoTotem;
    }

    public JLabel getjLabelTemperaturaAtual() {
        return jLabelTemperaturaAtual;
    }

    public void setjLabelTemperaturaAtual(JLabel jLabelTemperaturaAtual) {
        this.jLabelTemperaturaAtual = jLabelTemperaturaAtual;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCpuEmUso;
    private javax.swing.JLabel jLabelMemoriaRamDisponivel;
    private javax.swing.JLabel jLabelMemoriaRamEmUso;
    private javax.swing.JLabel jLabelMemoriaRamTotal;
    private javax.swing.JLabel jLabelNomeDoUsuario;
    private javax.swing.JLabel jLabelNumeroDeIdentificacaoDoTotem;
    private javax.swing.JLabel jLabelTemperaturaAtual;
    // End of variables declaration//GEN-END:variables
}
